
// Code generated by Temporary; DO NOT EDIT.
package temporary
import (
	"calebsideras.com/temporary/src/app/home_"
	"calebsideras.com/temporary/src/app/docs/index"
	"calebsideras.com/temporary/src/app/examples/_slug_/dynamic-routes"
	"calebsideras.com/temporary/src/app/docs/installation"
	"calebsideras.com/temporary/src/app/docs/routing/pages-and-index"
	"calebsideras.com/temporary/src/app/docs/routing/caching"
	"calebsideras.com/temporary/src/app/docs/routing/dependency-injection"
	"calebsideras.com/temporary/src/app/docs/pages"
	"calebsideras.com/temporary/src/app/docs/routing/static-pages-and-routes"
	"calebsideras.com/temporary/src/app/examples/static-render"
	"calebsideras.com/temporary/src/app/docs/project-structure"
	"calebsideras.com/temporary/src/app/examples/todo"
	"calebsideras.com/temporary/src/app/docs/pages/templ"
	"calebsideras.com/temporary/src/app/docs/routing/dynamic-routes"
	"calebsideras.com/temporary/src/app/docs/index/templ"
	"calebsideras.com/temporary/src/app/docs/routing/hx-boost"
	"calebsideras.com/temporary/src/app/examples/dependency-injection"
	"calebsideras.com/temporary/src/app/docs/introduction_"
	"calebsideras.com/temporary/src/app/docs/routing"
	"calebsideras.com/temporary/src/app"
	"calebsideras.com/temporary/src/app/examples/suspense"
	"calebsideras.com/temporary/src/app/docs/routing/suspense"
	"calebsideras.com/temporary/src/app/docs/routing/defining-routes"
	"calebsideras.com/temporary/src/app/examples/metadata"
	"calebsideras.com/temporary/src/app/docs/pages/static-pages"
)

var PathToIndex = map[string]string{
	"/docs/routing/defining-routes" : "/",
	"/docs/routing/hx-boost" : "/",
	"/docs/project-structure" : "/",
	"/examples/suspense" : "/",
	"/docs/routing/suspense" : "/",
	"/examples" : "/",
	"/examples/static-render" : "/",
	"/docs" : "/",
	"/docs/pages" : "/",
	"/examples/todo" : "/",
	"/docs/routing/dynamic-routes" : "/",
	"/examples/{slug}" : "/",
	"/docs/pages/templ" : "/",
	"/docs/routing/pages-and-index" : "/",
	"/docs/index/templ" : "/",
	"/examples/{slug}/dynamic-routes" : "/",
	"/docs/installation" : "/",
	"/docs/routing/dependency-injection" : "/",
	"/docs/routing/static-pages-and-routes" : "/",
	"/examples/dependency-injection" : "/",
	"/docs/routing" : "/",
	"/docs/routing/caching" : "/",
	"/docs/index" : "/",
	"/" : "/",
	"/docs/pages/static-pages" : "/",
	"/examples/metadata" : "/",
}

var Index = map[string]IndexProps{
	"/" : {"/", app.Index_, 0, 1, []string{}},
}

var PageStatic = []PageProps{
	{"/docs", docs_introduction.Page_, 0, []string{}},
	{"/docs/pages/templ", docs_pages_templ.Page_, 0, []string{}},
	{"/docs/routing/dynamic-routes", docs_routing_dynamicrouting.Page_, 0, []string{}},
	{"/docs/index/templ", docs_index_templ.Page_, 0, []string{}},
	{"/docs/index", docs_index.Page_, 0, []string{}},
	{"/docs/routing/defining-routes", docs_routingfundamentals.Page_, 0, []string{}},
	{"/docs/routing/dependency-injection", docs_routing_dependencyinjecton.Page_, 0, []string{}},
	{"/docs/routing/static-pages-and-routes", docs_routing_staticpagesandroutes.Page_, 0, []string{}},
	{"/examples/static-render", examples_staticrender.Page_, 0, examples_staticrender.Metadata},
	{"/docs/routing/hx-boost", docs_routing_hxboost.Page_, 0, []string{}},
	{"/docs/installation", docs_installation.Page_, 0, []string{}},
	{"/docs/project-structure", docs_projectstructure.Page_, 0, []string{}},
	{"/docs/routing", docs_routing.Page_, 0, []string{}},
	{"/", home.Page_, 0, home.Metadata},
	{"/docs/pages", docs_pages.Page_, 0, []string{}},
	{"/docs/routing/pages-and-index", docs_routing_pagesandindex.Page_, 0, []string{}},
	{"/examples/todo", examples_todo.Page_, 0, examples_todo.Metadata},
	{"/docs/pages/static-pages", docs_pages_staticpages.Page_, 0, []string{}},
	{"/docs/routing/caching", docs_routing_caching.Page_, 0, []string{}},
	{"/docs/routing/suspense", docs_routing_suspense.Page_, 0, []string{}},
}

var PageDynamic = []PageProps{
	{"/examples/{slug}/dynamic-routes", examples_dynamicroutes.Page, 2, examples_dynamicroutes.Metadata},
	{"/examples/metadata", metadata.Page, 0, metadata.Metadata},
	{"/examples/dependency-injection", examples_dependencyinjection.Page, 1, examples_dependencyinjection.Metadata},
	{"/examples/suspense", examples_suspense.Page, 0, examples_suspense.Metadata},
}

var RouteStatic = []RouteProps{
	{"/examples/{slug}/dynamic-routes/code", examples_dynamicroutes.Code_, 0},
	{"/examples/static-render/example", examples_staticrender.Example_, 0},
	{"/examples/static-render/code", examples_staticrender.Code_, 0},
	{"/examples/dependency-injection/code", examples_dependencyinjection.Code_, 0},
	{"/examples/todo/example", examples_todo.Example_, 0},
	{"/examples/todo/code", examples_todo.Code_, 0},
	{"/examples/suspense/code", examples_suspense.Code_, 0},
}

var RouteDynamic = []RouteProps{
	{"/examples/{slug}/dynamic-routes/example", examples_dynamicroutes.Example, 2},
	{"/examples/dependency-injection/example", examples_dependencyinjection.Example, 1},
	{"/examples/todo/add-task", examples_todo.AddTask, 2},
	{"/examples/suspense/example", examples_suspense.Example, 0},
}
