			
// Code generated by Temporary; DO NOT EDIT.

package temporary

import "calebsideras.com/temporary/src/utils"
		

// TEMPORARY STRUCT
type Temp struct {
	dependency utils.Hello3
	dependencyName string
}

		
// POINTER TO STRUCT
func NewTemp(dep interface{}) *Temp {
	t := &Temp{dependency: dep.(utils.Hello3)}
	t.init(dep)
	return t
}
